### ISSUE TITLE
test with docker compose script not working

### ISSUE THREAD

**Issue by jvalhondo** [neo4j-contrib/neomodel#427]
Running the script `./test_with_docker_compose.sh` seems not to be working properly as it exits with code 1:
`error: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
neomodel_tests_1 exited with code 1`

The full output can be found [here](https://pastebin.com/sFTyLfy2).

**Comment by aanastasiou** [comment]
Thank you for flagging this, the error is triggered by the tests (and `neomodel` functionality) of the spatial datatypes. Geos is [this one](https://trac.osgeo.org/geos/) and it gets installed with `shapely` (or one of its dependencies). Not sure why this is not hapenning when this bash script runs the installation process.

Is it possible to manually add `libgeos` to the docker image as part of that script?

**Comment by jvalhondo** [comment]
I got back into this issue again and got `shapely` properly installed.
I had to include the following `apk add --no-cache gcc libc-dev geos-dev`, leaving the  `docker-compose-file` as follows:

```
version: "3"

services:
  tests:
    image: "python:${PYTHON_VERSION}-alpine"
    volumes:
      - .:/src
      - pip-cache:/root/.cache/pip
    working_dir: /src
    command: sh -c "echo "http://mirror.leaseweb.com/alpine/edge/testing" >> /etc/apk/repositories; apk add --no-cache gcc libc-dev geos-dev; pip install shapely; while ! nc neo4j 7687; do  sleep 1; done; python -B setup.py test"
    links:
      - neo4j
    environment:
      NEO4J_BOLT_URL: bolt://neo4j:neo4j@neo4j:7687
  neo4j:
    image: "neo4j:${NEO4J_VERSION}"
    environment:
      NEO4J_AUTH: none

volumes:
  pip-cache:
    driver: local
```

How ever it leads to 3 tests failures in `test/test_contrib/test_spatial_properties.py`
The full output can be found [here](https://gist.github.com/jvalhondo/76c4f558653df477ebfaac9525fcc7f7) 

@aanastasiou any insight to sort it out? :)
