### ISSUE TITLE
StructuredNode.nodes.get() and ...all() return id is depricated error

### ISSUE THREAD

**Issue by PibeChorro** [neo4j-contrib/neomodel#850]
## Expected Behavior (Mandatory)
I want to get a node (a user in my case) based on the `name` property and check if the correct password was submitted using the `User.nodes.get()` method. This should return a node of type User if it exists and the password is correct

## Actual Behavior (Mandatory)
However, this method returns the "id is deprecated in Neo4j version 5, please migrate to element_id. If you use the id in a Cypher query, replace id() by elementId()." Error message

## How to Reproduce the Problem
My `User` class is pretty simple:
```
class User(StructuredNode):
    # Properties
    uid = UniqueIdProperty()
    username = StringProperty(required=True, unique_index=True)
    email = EmailProperty(required=True)
    password = StringProperty(required=True)
```
and so is my authentication method:
```
class LoginView(TokenObtainPairView):
    def post(self, request, *args, **kwargs):
      username = request.data.get('username')
      password = request.data.get('password')
      user = User.nodes.get(username=username)      
      if user is not None and user.password == password:
        refresh = RefreshToken.for_user(user)
        return JsonResponse({
          'refresh': str(refresh),
          'access': str(refresh.access_token),
        })
      else:
        return JsonResponse({'error': 'Invalid credentials'}, status=400)
```
### Simple Example
I just try to make a post request using Postman to my Django `LoginView` page with username and password credentials

## Specifications (Mandatory)
I run my project with a Django Docker image and a neo4j Docker image. The `docker-compose.ylm` looks as follows:<br>
```
services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # Mount Django app files for live development
    ports:
      - "8000:8000"  # Django development server
    command: python manage.py runserver 0.0.0.0:8000

  neo4j:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      NEO4J_AUTH: neo4j/test1234  # Username/password for Neo4j
    ports:
      - "7474:7474"  # Neo4j browser interface
      - "7687:7687"  # Neo4j Bolt protocol
```

The Django Docker image is a simple python image that installs Django and neomodel:
```
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Install Django and other Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose Django's default port
EXPOSE 8000

# Command to run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```
and the neo4j Docker is just the latest official neo4j Image.<br>

This results for me in having neo4j version 5.24.1 and neomodel version 5.4.2

I don't know what I am doing wrong. I am not a really experienced programmer nor do I know much about databases. I just want to try a little project of my own, so if you find the time to answer me, please write for a complete noob.<br>

Kind regards and thanks in advance

## EDIT
It appears that the error is raised, because `neomodel` tries to get the `element_id` as an integer, but in my database `element_id` is not a simple number but looks like this:<br> <elementId>: 4:153291a0-162b-4dc2-a6ca-e30f56bf6edb:1

As far as I understand the number after the last colon is the id neomodel wants, right?
